version: 0.0
os: linux
files:
  - source: ./demo-0.0.1-SNAPSHOT.jar
    destination: /srv
  - source: ./server-start.sh
    destination: /srv/scripts
  - source: ./server-stop.sh
    destination: /srv/scripts
Hooks:
  ApplicationStart:
    - location: /srv/scripts/server-start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /srv/scripts/server-stop.sh
      timeout: 300
      runas: root
